services:
  - type: web
    name: main
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: DB_HOST
        value: 13.41.199.227
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: root123
      - key: DB_PORT
        value: 3309
      - key: DB_NAME
        value: carsautomation
